<!-- BEGIN -->
@import gg.jte.Content
@param Content content = null
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Пользователи</title>
</head>
<body>
<header>
    <p>
        <a href="/">Главная страница</a>
        <a href="/users">Список пользователей</a>
    </p>
</header>
${content}
<footer>Footer</footer>
</body>
</html>
<!-- END -->
